Install pip in CI

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -25,9 +25,23 @@ jobs:
       uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
-        
-    - name: Install R packages        
-      run: | 
+
+    - name: Verify Python version
+      run: |
+        python_version=$(python3 -c "import sys; print('.'.join(map(str, sys.version_info[:2])))")
+        if [ "$python_version" != "${{ matrix.python-version }}" ]; then
+          echo "ERROR: Python version mismatch. Got $python_version but expected ${{ matrix.python-version }}"
+          exit 1
+        fi
+
+    # When using setup-python with rocker/r2u:22.04, pip is not available for some reason
+    - name: Install pip
+      run: |
+        apt-get update
+        apt-get install -y python3-pip
+
+    - name: Install R packages
+      run: |
         Rscript -e "install.packages(c('remotes'))"
         Rscript -e "remotes::install_github('sebsilas/melsim')"
 
